[workspace]
members = ["contracts/*"]
resolver = "2"

[workspace.dependencies]
cw2 = "2"

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
panic = 'abort'
debug = false
debug-assertions = false
